# Generated by Django 4.2.2 on 2023-06-18 06:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_description",
                    models.CharField(max_length=300, verbose_name="описание работ"),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "работы",
                "verbose_name_plural": "перечень работ",
                "ordering": ["report__year", "report__month", "date"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(verbose_name="месяц")),
                ("year", models.IntegerField(verbose_name="год")),
                (
                    "stake",
                    models.IntegerField(
                        default=None, verbose_name="стоимость за 1 ч/д"
                    ),
                ),
            ],
            options={
                "verbose_name": "ежемесячный отчёт",
                "verbose_name_plural": "отчёты",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stake", models.IntegerField()),
                ("reports_email", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "настройки",
                "verbose_name_plural": "настройки",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "verbose_name": "исполнитель",
                "verbose_name_plural": "исполнители",
            },
        ),
        migrations.CreateModel(
            name="WorkerJobRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "job_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="reports.jobrecord",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="reports.worker",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StakeSetting",
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="reports.report",
                verbose_name="месяц",
            ),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="workers",
            field=models.ManyToManyField(
                related_name="job",
                through="reports.WorkerJobRecord",
                to="reports.worker",
                verbose_name="исполнители",
            ),
        ),
    ]
