version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: platinum_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - platinum_net
    restart: unless-stopped
    command: postgres -c listen_addresses='*'

  nginx:
    image: nginx:alpine
    container_name: postgres_nginx
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/staticfiles
    networks:
      - platinum_net
    restart: unless-stopped
    depends_on:
      - platinum

  platinum:
    image: vladiakimenko/platinum:latest
    container_name: platinum_django
    env_file:
      - .env
    networks:
      - platinum_net
    volumes:
      - staticfiles:/app/staticfiles
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  platinum_net:
    driver: bridge

volumes:
  pgdata:
    driver: local
  staticfiles:
    driver: local

